employee/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from aplications.employees import views
from django.conf import settings
from django.conf.urls.static import static
# Con esta variable se da un nombre a el conjunto de urls
app_name = "externas_app"

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('aplications.employees.url')),
    path('', include('aplications.departments.url')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplications/employees/models.py
from django.db import models
from aplications.departments.models import Department


class Skill(models.Model):
    skill = models.CharField('skill', max_length=50)

    class Meta:
        db_table = 'habilidad'
        verbose_name_plural = 'habilidad empleado'

    def __str__(self):
        return f'{self.id} {self.skill}'


class Employee(models.Model):

    JOB_CHOICES = (
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'OTRO'),
    )

    first_name = models.CharField('Nombre', max_length=60)
    last_name = models.CharField('apellido', max_length=60)
    full_name = models.CharField('NombreCompleto', max_length=150, blank=True)
    job = models.CharField('ocupaciòn', max_length=1, choices=JOB_CHOICES)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    #Creacion de relacion muchos a muchos
    skills = models.ManyToManyField(Skill)

    class Meta:
        db_table = 'empleado'
        verbose_name = 'empleado'
        verbose_name_plural = 'Empleado de la empresa'
        ordering = ['first_name', 'last_name']

    def __str__(self):
        return f'{self.job} {self.first_name} {self.last_name}'

aplications/employees/forms.py
from django import forms
from .models import Employee


class EmployeForm(forms.ModelForm):
    """Form definition for employe."""
    print("********************")

    class Meta:
        """Meta definition for employeform."""

        model = Employee
        fields = ('first_name',
                  'last_name',
                  'job',
                  'department',
                  'avatar',
                  'skills',)

        """ Widgets: es un diccionario,  Se usan para personalizar los formularios
             https://docs.djangoproject.com/en/4.2/ref/forms/widgets/
             https://rutan-medellin.udemy.com/course/curso-profesional-de-programacion-web-con-python-y-django/learn/lecture/17022628#overview
        """
        widgets = {'skills': forms.CheckboxSelectMultiple(
            # datos de personalizacion opcionales
            # attrs={
            #     'placeholder': 'nombre solo letras'
            # }
        )
        }

    """ metodo q se reescribe para validar los campos de un formulario
        https://docs.djangoproject.com/en/4.2/ref/forms/widgets/
    """

    # def clean_first_name(self):
    #     # Se recupera la info que viene en el formulario
    #     # en este caso validare el nombre
    #     nombre = self.cleaned_data['first_name']
    #     if nombre.isalnum():
    #         print(nombre)
    #         raise forms.ValidationError('Deben ser letras no numeros')
    #     return nombre

aplications/employees/views.py
from typing import Any, Dict
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView, CreateView, TemplateView, UpdateView, DeleteView
from aplications.employees.models import Employee
from django.urls import reverse_lazy
from .forms import EmployeForm


class MainView(TemplateView):
    """ start view """
    template_name = 'index.html'


"""
al usar paginator_by el mostrara los x registros q se den
encada pagina y la forma de ver cada pagina seria
http://127.0.0.1:8000/listar/?page=2
"""


class DisplayAll(ListView):
    template_name = 'employee/list_all.html'
    paginate_by = 5
    ordering = 'first_name'

    def get_queryset(self):
        # retorna una lista Quersyset
        parameter = self.request.GET.get('kword', '')
        lista = Employee.objects.filter(first_name__icontains=parameter)
        return lista
# class DisplayByDepartment(ListView):
#   # Lo que esta abajo son atributos de ListView
#     template_name = 'employe/list_by_dep.html'
#     queryset = Employee.objects.filter(department__name='contaduria')

  # Usando parametro en la url se reescribe el metodo
  # get_queryset(self)
  # Sl no tener el queryset se hace necesario agregar el m,odel


class ListEmployeeAdmin(ListView):
    template_name = 'employee/list_employee_admin.html'
    paginate_by = 5
    ordering = 'first_name'
    context_object_name = 'employee'
    model = Employee


"""
  The class DisplayByDepartment is a subclass of ListView that displays a list of employees  filtered by department.
"""


class EmployeeByDetail(DeleteView):
    model = Employee
    template_name = 'employee/employee_detail.html'

    def get_context_data(self, **kwargs):
        context = super(EmployeeByDetail, self).get_context_data(**kwargs)
        context['titulo'] = 'EMPLEADO DEL MES'
        return context


class EmployeeByDepartment(ListView):
    # Lo que esta abajo son atributos de ListView
    template_name = 'employee/list_by_department.html'
    context_object_name = 'employee'
    paginate_by = 4

    def get_queryset(self):
        # retorna una lista Quersyset
        # Recibe un parametro en la url llamado shorname
        parameter = self.kwargs['shorname']
        list_employee = Employee.objects.filter(
            department__short_name=parameter)
        return list_employee


class DisplayByName(ListView):
    # Lo que esta abajo son atributos de ListView
    template_name = 'employee/clave.html'

    def get_queryset(self):
        # retorna una lista Quersyset
        parametro = self.request.GET.get('nombre',)
        lista = Employee.objects.filter(first_name=parametro)
        print(lista)
        return lista


"""
  La vista TemplateView solo sirve para mostar un templete o html
  solo usa 1 atributos
  * templete_name

"""


class Gracias(TemplateView):
    template_name = 'employee/gracias.html'


"""
  Crea un formulario para accesar registros en la bd
  siempre debe llevar el atributo
  * fields = () que puede ser una lista o (__all__), estos son
    los  campos del modelo que pueden ser todos o algunos
  * success_url = '.' usado para redireccionar
  * reverse_lazy = se usa para redireccionar urls por nombre de
    url
    video 49
"""


# class EmployeCreateView(CreateView):
#     template_name = "employe/add.html"
#     model = Employee
#     #fields = ['first_name', 'job']
#     fields = ('__all__')
#     #success_url = '.'
#     success_url = reverse_lazy('internas_app:gracias')


"""
   En caso de usar form_valid
   form que crea createview no muestre el campo fullname NO significa que el campo no exista en el form y al momento de instanciarlo puedo acceder a el normalmente

"""


class EmployeeFormCreateView(CreateView):
    template_name = "employee/create_employee.html"
    model = Employee
    form_class = EmployeForm
    # fields = ['first_name', 'job']
    # success_url = '.'
    success_url = reverse_lazy('employee_app:list_admin')

    def form_valid(self, form):
        # logica del proceso
        empleado = form.save()
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmployeeFormCreateView, self).form_valid(form)


"""
 Uso de la vista generica UpdateView
 * necesita de un parametro para saber a que registro debe actualizar
 * la url requiere de una <pk>
 * requiere del field []
 * success_url =

"""


"""
  The EmployeeUpdateView class is a view for updating employee information and redirects to a success page after successful update.
"""


class EmployeeUpdateView(UpdateView):
    template_name = "employee/update_employee.html"
    model = Employee
    fields = fields = ['first_name',
                       'last_name',
                       'department',
                       'job',
                       'skills',
                       ]
    # success_url = '.'
    success_url = reverse_lazy('employee_app:list_admin')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        # logica del proceso
        empleado = form.save()
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmployeeUpdateView, self).form_valid(form)


"""
  Vista generica DeleteView
  requiere:
  * model
  * template_name
  * success_url = 
"""

"""
  The EmployeeDeleteView class is a view for deleting an Employee object and redirects to the
  employee_app:list_admin URL upon successful deletion.
"""


class EmployeeDeleteView(DeleteView):
    model = Employee
    template_name = "employee/delete_employee.html"

    # success_url = '.'
    success_url = reverse_lazy('employee_app:list_admin')


"""
  Vista creada para hacer la practica del model.form
  en este caso no usara el fields ya que viene defnido desde el employeForm
  y se renderizara usando el form_class
  * De esta manera podremos editar los campos del formulario de la variable form
    en el html
  
"""


"""
The `EmployeFormCreateView` class is a view for creating a new employee record using a form, with a custom template and success URL.
"""


# class EmployeFormCreateView(CreateView):
#     template_name = "employee/prueba_form.html"
#     model = Employee
#     #fields = ['first_name', 'last_name', 'job',]
#     form_class = EmployeForm
#     # success_url = '.'
#     success_url = reverse_lazy('internas_app:gracias')

#     # def form_valid(self, form):
#     #     # logica del proceso
#     #     empleado = form.save()
#     #     empleado.full_name = empleado.firt_name + ' ' + empleado.last_name
#     #     empleado.save()
#     #     return super(EmployeCreateView, self).form_valid(form)

templates/employee/clave.html
<h1>Buscar empleado por nombre</h1>

<form method="GET">
  {% csrf_token %}
  <input type="text" id="nombre" name="nombre" placeholder="Ingresa nombre" />
  <button type="submit">Enviar</button>
</form>

<h2>Lista de empleados</h2>
<ul>
  {% for e in object_list %}
  <li>{{e}}</li>
  {% endfor%}
</ul>

templates/employee/create_employee.html
{% extends 'base.html' %}
{% block title%}
Crear empleado
{% endblock title%}
{% block body %}
{% include 'includes/header.html' %}
<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">
      Registrar empleado
    </h1>
    <div class="cell">
      <form class="grid-x grid-margin-x" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="cell large-6 medium-6 small-12">
          <label>Nombre
            {{ form.first_name }}
          </label>
        </div>
        <div class="cell large-6 medium-6 small-12">
          <label>Apellido
            {{ form.last_name }}
          </label>
        </div>
        <div class="cell large-6 medium-6 small-12">
          <label>Area
            {{ form.department }}
          </label>
        </div>
        <div class="cell large-6 medium-6 small-12">
          <label>Cargo
            {{ form.job }}
          </label>
        </div>
        <div class="cell large-6 medium-6 small-12">
          <label>Habilidades
            {{ form.skills }}
          </label>
          <div class="cell large-6 medium-6 small-12">
            <label>foto
              {{ form.avatar }}
            </label>
          </div>
          <div class="cell large-12 medium-12 small-12">
            <button type="submit" class="submit success button">Registrar</button>
          </div>
      </form>
    </div>
  </div>
</div>
{% endblock body %}

templates/employee/delete_employee.html
{% extends 'base.html' %}
{% block title%}
Eliminar empleado
{% endblock title%}
{% block body %}
{% include 'includes/header.html' %}
<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell"> Eliminar empleado: {{object.full_name}}</h1>
    <form class="cell" method="POST">
      {% csrf_token %}
      <div class="cell callout alert">
        <h4>Estas seguro de eliminar el empleado?</h4>
        <button class="alert button">Eliminar</button>
      </div>
    </form>
  </div>
</div>

{% endblock body %}

templates/employee/employee_detail.html
{% extends 'base.html' %} {% load static %} {% block title %} {{object.full_name}}
{% endblock title %} {% block body %} {% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x grid-margin-x align-center">

    <div class="card cell large-4 small-12 medium-4" style="width: 300px; margin-top: 15px;">
      <div class="" style="text-align: center; background-color: rgba(243, 243, 243, 0.705); margin: 10px;">
        {{object.get_job_display}}
      </div>
      {% if object.avatar %}
      <img src="{{ object.avatar.url }}">
      {% else %}
      <img src="{% static 'img/no-disponible.jpg' %}">
      {% endif %}

      <div class="card-section" style="text-align: center;">
        <h4>{{object.full_name}}</h4>
        <p>{{object.first_name}}</p>
        <p>{{object.last_name}}</p>
        <p>{{object.department.short_name}}</p>
        <p class="label">Habilidades</p>
        <ul>
          {% for skill in object.skills.all %}
          <li>{{skill.skill}}</li>
          {% endfor %}

        </ul>

      </div>
    </div>

  </div>
</div>
{% endblock body %}

templates/employee/list_all.html
{% extends 'base.html' %} {% block title %} Lista de los empleados de la empresa
{% endblock title %} {% block body %} {% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell small-12 large-12">Lista de empleados</h1>
    <form method="GET" class="cell grid-x grid-margin-x">{% csrf_token %}
      <div class="cell large-7">
        <input type="text" placeholder="empleado" name="kword" id="kword">
      </div>
      <div class="cell large-2">
        <button type="submit" class="button success">Buscar</button>
      </div>
    </form>

    <div class="cell">
      <table class="stack">
        <thead>
          <tr>
            <th width="200">ID</th>
            <th>Nombre</th>
            <th width="150">Apellido</th>
            <th width="150">Departamento</th>
            <th width="150">Acciòn</th>
          </tr>
        </thead>
        <tbody>
          {% for e in object_list %}
          <tr>
            <td>{{ e.id }}</td>
            <td>{{ e.first_name }}</td>
            <td>{{ e.last_name }}</td>
            <td>{{ e.department }}</td>
            <td>
              <a class="button warning" href="{% url 'employee_app:detalle' e.id %}">ver</a>
            </td>
          </tr>
          {% endfor %}

        </tbody>
      </table>
    </div>
    <div class="cell">
      {% if is_paginated %}
      <nav aria-label="Pagination">
        <ul class="pagination text-center">
          {% if page_obj.has_previous %}
          <li class="pagination-previous">
            <a href="?page={{page_obj.previous_page_number}}">Atras</a>
          </li>
          {% endif%}
          {% for pagina in page_obj.paginator.page_range %}
          {% if pagina == page_obj.number %}
          <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
          {% else %}
          <li><a href="?page={{ pagina }}">{{ pagina }}</a></li>
          {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
          <li class="pagination-next">
            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
          </li>
          {% endif%}
        </ul>
      </nav>
      {% endif %}

    </div>
  </div>
</div>
{% endblock body %}

templates/employee/list_by_department.html
{% extends 'base.html' %}

{% block title %}
Empleados por departamento
{% endblock title%}

{% block body %}
{% include "includes/header.html" %}
<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell small-12 large-12">Lista de empleados por departamento</h1>

    <div class="cell">
      <table class="stack">
        <thead>
          <tr>
            <th width="200">ID</th>
            <th>Nombre</th>
            <th width="150">Apellido</th>
            <th width="150">Departamento</th>
            <th width="150">Acciòn</th>
          </tr>
        </thead>
        <tbody>
          {% for e in employee %}
          <tr>
            <td>{{ e.id }}</td>
            <td>{{ e.first_name }}</td>
            <td>{{ e.last_name }}</td>
            <td>{{ e.department }}</td>
            <td>
              <a class="button warning" href="{% url 'employee_app:detalle' e.id %}">ver</a>
            </td>
          </tr>
          {% endfor %}

        </tbody>
      </table>
    </div>
    <div class="cell">
      {% if is_paginated %}
      <nav aria-label="Pagination">
        <ul class="pagination text-center">
          {% if page_obj.has_previous %}
          <li class="pagination-previous">
            <a href="?page={{page_obj.previous_page_number}}">Atras</a>
          </li>
          {% endif%}
          {% for pagina in page_obj.paginator.page_range %}

          <li><a href="?page={{ pagina }}">{{ pagina }}</a></li>

          {% endfor %}
          {% if page_obj.has_next %}
          <li class="pagination-next">
            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
          </li>
          {% endif%}
        </ul>
      </nav>
      {% endif %}

    </div>
  </div>
</div>
{% endblock body %}

templates/employee/list_employee_admin.html
{% extends 'base.html' %} {% block title %} Lista de los empleados en admin
{% endblock title %} {% block body %} {% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell small-12 large-12">Lista de empleados</h1>
    <div class="cell">
      <table class="stack">
        <thead>
          <tr>
            <th width="100">ID</th>
            <th>Nombre</th>
            <th width="150">Apellido</th>
            <th width="150">Departamento</th>
            <th style="text-align: center;" width="70">Acciòn</th>
          </tr>
        </thead>
        <tbody>
          {% for e in object_list %}
          <tr>
            <td>{{ e.id }}</td>
            <td>{{ e.first_name }}</td>
            <td>{{ e.last_name }}</td>
            <td>{{ e.department }}</td>
            <td>
              <a class="button success" href="{% url 'employee_app:update_employee' e.id %}">Editar</a>
            </td>
            <td>
              <a class="button alert" href="{% url 'employee_app:delete_employee' e.id %}">Eliminar</a>
            </td>
          </tr>
          {% endfor %}

        </tbody>
      </table>
    </div>
    <div class="cell">
      {% if is_paginated %}
      <nav aria-label="Pagination">
        <ul class="pagination text-center">
          {% if page_obj.has_previous %}
          <li class="pagination-previous">
            <a href="?page={{page_obj.previous_page_number}}">Atras</a>
          </li>
          {% endif%}
          {% for pagina in page_obj.paginator.page_range %}
          {% if pagina == page_obj.number %}
          <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
          {% else %}
          <li><a href="?page={{ pagina }}">{{ pagina }}</a></li>
          {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
          <li class="pagination-next">
            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
          </li>
          {% endif%}
        </ul>
      </nav>
      {% endif %}

    </div>
  </div>
</div>
{% endblock body %}

templates/employee/new_department.html.html
<h1>Prueba de formularo con models.form</h1>

<form method="POST">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">enviar</button>
</form>

templates/employee/update_employee.html
{% extends 'base.html' %} {% block title %} actualizar empleado
{% endblock title %} {% block body %} {% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">
      Modificar empleado
    </h1>
    <div class="cell">
      <form class="grid-x grid-margin-x" method="post">{% csrf_token %}
        <div class="cell large-6 medium-6 small-12">
          <label>Nombre
            {{ form.first_name }}
          </label>
        </div>
        <div class="cell large-6 medium-6 small-12">
          <label>Apellido
            {{ form.last_name }}
          </label>
        </div>
        <div class="cell large-6 medium-6 small-12">
          <label>Area
            {{ form.department }}
          </label>
        </div>
        <div class="cell large-6 medium-6 small-12">
          <label>Cargo
            {{ form.job }}
          </label>
        </div>
        <div class="cell large-6 medium-6 small-12">
          <label>Habilidades
            {{ form.skills }}
          </label>
        </div>
        <div class="cell large-12 medium-12 small-12">
          <button type="submit" class="submit success button">Guardar</button>
        </div>

      </form>

    </div>

  </div>

</div>

{% endblock body %}